development:
  adapter: postgresql
  encoding: unicode
  database: simple-sign-up
  pool: 5
  username: WorkLaptop
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: simple-sign-up-test
  pool: 5
  username: WorkLaptop
  password: